# Cloud Build configuration for Cloud Run (backend) + Firebase Hosting (frontend)
# Triggered by branch push: develop -> dev, main -> prod
# Substitution variables: _ENV (dev|prod), _REGION (us-central1)

substitutions:
  _ENV: dev
  _REGION: us-central1

steps:
  # Step 1: Build and deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        gcloud run deploy sammy-backend-${_ENV} \
          --source . \
          --region ${_REGION} \
          --allow-unauthenticated \
          --set-secrets="FIREBASE_SERVICE_ACCOUNT=FIREBASE_SERVICE_ACCOUNT:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest" \
          --set-env-vars="NODE_ENV=${_ENV}" \
          --set-env-vars="^@^ALLOWED_ORIGINS=https://sammy-658.web.app,https://sammy-658-dev.web.app,capacitor://localhost"

  # Step 2: Get Cloud Run URL and create frontend env file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLOUD_RUN_URL=$$(gcloud run services describe sammy-backend-${_ENV} --region ${_REGION} --format='value(status.url)')
        echo "VITE_API_URL=$${CLOUD_RUN_URL}/api" > /workspace/frontend/.env.production
        cat /workspace/frontend/.env.production

  # Step 3: Install frontend dependencies and build
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        cat .env.production || echo "No .env.production found"
        npm ci
        npm run build

  # Step 4: Deploy frontend to Firebase Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project sammy-658

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
