runtime: nodejs22
instance_class: F1
env_variables:
  NODE_ENV: production
  # Add other env vars here or in Cloud Build triggers
automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
